package com.h4h.employeeportal.config;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

/**
 * This class generates hashed passwords using BCryptPasswordEncoder for updating
 * passwords in the application.properties file.
 *
 * It demonstrates how to securely hash a password using BCryptPasswordEncoder
 * from Spring Security. The hashed passwords generated by this class should be
 * used to replace the existing password in the application.properties file.
 */
public class PasswordEncoderGenerator {
    public static void main(String[] args) {

        int i = 0;
        while (i < 10) {
            String password = "admin";
            BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
            String hashedPassword = passwordEncoder.encode(password);

            System.out.println(hashedPassword);
            i++;
        }
    }
}
